repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: check-ruff-versions
        name: Check Ruff versions match
        entry: poetry run python scripts/check_ruff_versions.py
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--exit-non-zero-on-fix]

  - repo: local
    hooks:
      - id: prevent-main-commit
        name: Prevent commits to main branch
        entry: bash -c 'if [[ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]]; then echo "Do not commit directly to the main branch"; exit 1; fi'
        language: system
        stages: [commit]
