from pyboy import PyBoyMemoryView
from pydantic import BaseModel, ConfigDict

from emulator.enums import MapLocation

_INT_TO_MAP_NAME = {
    0x00: MapLocation.PALLET_TOWN,
    0x01: MapLocation.VIRIDIAN_CITY,
    0x02: MapLocation.PEWTER_CITY,
    0x03: MapLocation.CERULEAN_CITY,
    0x04: MapLocation.LAVENDER_TOWN,
    0x05: MapLocation.VERMILION_CITY,
    0x06: MapLocation.CELADON_CITY,
    0x07: MapLocation.FUCHSIA_CITY,
    0x08: MapLocation.CINNABAR_ISLAND,
    0x09: MapLocation.INDIGO_PLATEAU,
    0x0A: MapLocation.SAFFRON_CITY,
    0x0C: MapLocation.ROUTE_1,
    0x0D: MapLocation.ROUTE_2,
    0x0E: MapLocation.ROUTE_3,
    0x0F: MapLocation.ROUTE_4,
    0x10: MapLocation.ROUTE_5,
    0x11: MapLocation.ROUTE_6,
    0x12: MapLocation.ROUTE_7,
    0x13: MapLocation.ROUTE_8,
    0x14: MapLocation.ROUTE_9,
    0x15: MapLocation.ROUTE_10,
    0x16: MapLocation.ROUTE_11,
    0x17: MapLocation.ROUTE_12,
    0x18: MapLocation.ROUTE_13,
    0x19: MapLocation.ROUTE_14,
    0x1A: MapLocation.ROUTE_15,
    0x1B: MapLocation.ROUTE_16,
    0x1C: MapLocation.ROUTE_17,
    0x1D: MapLocation.ROUTE_18,
    0x1E: MapLocation.ROUTE_19,
    0x1F: MapLocation.ROUTE_20,
    0x20: MapLocation.ROUTE_21,
    0x21: MapLocation.ROUTE_22,
    0x22: MapLocation.ROUTE_23,
    0x23: MapLocation.ROUTE_24,
    0x24: MapLocation.ROUTE_25,
    0x25: MapLocation.YOUR_HOUSE_1F,
    0x26: MapLocation.YOUR_HOUSE_2F,
    0x27: MapLocation.RIVALS_HOUSE,
    0x28: MapLocation.OAKS_LAB,
    0x29: MapLocation.VIRIDIAN_POKECENTER,
    0x2A: MapLocation.VIRIDIAN_MART,
    0x2B: MapLocation.VIRIDIAN_SCHOOL,
    0x2C: MapLocation.VIRIDIAN_HOUSE,
    0x2D: MapLocation.VIRIDIAN_GYM,
    0x2E: MapLocation.DIGLETTS_CAVE_ROUTE2,
    0x2F: MapLocation.VIRIDIAN_FOREST_NORTH_GATE,
    0x30: MapLocation.ROUTE_2_HOUSE,
    0x31: MapLocation.ROUTE_2_GATE,
    0x32: MapLocation.VIRIDIAN_FOREST_SOUTH_GATE,
    0x33: MapLocation.VIRIDIAN_FOREST,
    0x34: MapLocation.MUSEUM_1F,
    0x35: MapLocation.MUSEUM_2F,
    0x36: MapLocation.PEWTER_GYM,
    0x37: MapLocation.PEWTER_HOUSE_1,
    0x38: MapLocation.PEWTER_MART,
    0x39: MapLocation.PEWTER_HOUSE_2,
    0x3A: MapLocation.PEWTER_POKECENTER,
    0x3B: MapLocation.MT_MOON_1F,
    0x3C: MapLocation.MT_MOON_B1F,
    0x3D: MapLocation.MT_MOON_B2F,
    0x3E: MapLocation.CERULEAN_TRASHED_HOUSE,
    0x3F: MapLocation.CERULEAN_MELANIES_HOUSE,
    0x40: MapLocation.CERULEAN_POKECENTER,
    0x41: MapLocation.CERULEAN_GYM,
    0x42: MapLocation.BIKE_SHOP,
    0x43: MapLocation.CERULEAN_MART,
    0x44: MapLocation.MT_MOON_POKECENTER,
    0x46: MapLocation.ROUTE_5_GATE,
    0x47: MapLocation.UNDERGROUND_PATH_ROUTE5,
    0x48: MapLocation.DAYCARE,
    0x49: MapLocation.ROUTE_6_GATE,
    0x4A: MapLocation.UNDERGROUND_PATH_ROUTE6,
    0x4C: MapLocation.ROUTE_7_GATE,
    0x4D: MapLocation.UNDERGROUND_PATH_ROUTE7,
    0x4F: MapLocation.ROUTE_8_GATE,
    0x50: MapLocation.UNDERGROUND_PATH_ROUTE8,
    0x51: MapLocation.ROCK_TUNNEL_POKECENTER,
    0x52: MapLocation.ROCK_TUNNEL_1F,
    0x53: MapLocation.POWER_PLANT,
    0x54: MapLocation.ROUTE_11_GATE_1F,
    0x55: MapLocation.DIGLETTS_CAVE_ROUTE11,
    0x56: MapLocation.ROUTE_11_GATE_2F,
    0x57: MapLocation.ROUTE_12_GATE_1F,
    0x58: MapLocation.BILLS_HOUSE,
    0x59: MapLocation.VERMILION_POKECENTER,
    0x5A: MapLocation.FAN_CLUB,
    0x5B: MapLocation.VERMILION_MART,
    0x5C: MapLocation.VERMILION_GYM,
    0x5D: MapLocation.VERMILION_HOUSE_1,
    0x5E: MapLocation.VERMILION_DOCK,
    0x5F: MapLocation.SS_ANNE_1F,
    0x60: MapLocation.SS_ANNE_2F,
    0x61: MapLocation.SS_ANNE_3F,
    0x62: MapLocation.SS_ANNE_B1F,
    0x63: MapLocation.SS_ANNE_BOW,
    0x64: MapLocation.SS_ANNE_KITCHEN,
    0x65: MapLocation.SS_ANNE_CAPTAINS_ROOM,
    0x66: MapLocation.SS_ANNE_1F_ROOMS,
    0x67: MapLocation.SS_ANNE_2F_ROOMS,
    0x68: MapLocation.SS_ANNE_B1F_ROOMS,
    0x6C: MapLocation.VICTORY_ROAD_1F,
    0x71: MapLocation.LANCES_ROOM,
    0x76: MapLocation.HALL_OF_FAME,
    0x77: MapLocation.UNDERGROUND_PATH_NORTH_SOUTH,
    0x78: MapLocation.CHAMPIONS_ROOM,
    0x79: MapLocation.UNDERGROUND_PATH_EAST_WEST,
    0x7A: MapLocation.CELADON_MART_1F,
    0x7B: MapLocation.CELADON_MART_2F,
    0x7C: MapLocation.CELADON_MART_3F,
    0x7D: MapLocation.CELADON_MART_4F,
    0x7E: MapLocation.CELADON_MART_ROOF,
    0x7F: MapLocation.CELADON_MART_ELEVATOR,
    0x80: MapLocation.CELADON_MANSION_1F,
    0x81: MapLocation.CELADON_MANSION_2F,
    0x82: MapLocation.CELADON_MANSION_3F,
    0x83: MapLocation.CELADON_MANSION_ROOF,
    0x84: MapLocation.CELADON_MANSION_ROOF_HOUSE,
    0x85: MapLocation.CELADON_POKECENTER,
    0x86: MapLocation.CELADON_GYM,
    0x87: MapLocation.GAME_CORNER,
    0x88: MapLocation.CELADON_MART_5F,
    0x89: MapLocation.GAME_CORNER_PRIZE_ROOM,
    0x8A: MapLocation.CELADON_DINER,
    0x8B: MapLocation.CELADON_HOUSE,
    0x8C: MapLocation.CELADON_HOTEL,
    0x8D: MapLocation.LAVENDER_POKECENTER,
    0x8E: MapLocation.POKEMON_TOWER_1F,
    0x8F: MapLocation.POKEMON_TOWER_2F,
    0x90: MapLocation.POKEMON_TOWER_3F,
    0x91: MapLocation.POKEMON_TOWER_4F,
    0x92: MapLocation.POKEMON_TOWER_5F,
    0x93: MapLocation.POKEMON_TOWER_6F,
    0x94: MapLocation.POKEMON_TOWER_7F,
    0x95: MapLocation.LAVENDER_HOUSE_1,
    0x96: MapLocation.LAVENDER_MART,
    0x97: MapLocation.LAVENDER_HOUSE_2,
    0x98: MapLocation.FUCHSIA_MART,
    0x99: MapLocation.FUCHSIA_HOUSE_1,
    0x9A: MapLocation.FUCHSIA_POKECENTER,
    0x9B: MapLocation.FUCHSIA_HOUSE_2,
    0x9C: MapLocation.SAFARI_ZONE_GATE,
    0x9D: MapLocation.FUCHSIA_GYM,
    0x9E: MapLocation.FUCHSIA_MEETING_ROOM,
    0x9F: MapLocation.SEAFOAM_ISLANDS_B1F,
    0xA0: MapLocation.SEAFOAM_ISLANDS_B2F,
    0xA1: MapLocation.SEAFOAM_ISLANDS_B3F,
    0xA2: MapLocation.SEAFOAM_ISLANDS_B4F,
    0xA3: MapLocation.VERMILION_HOUSE_2,
    0xA4: MapLocation.VERMILION_HOUSE_3,
    0xA5: MapLocation.POKEMON_MANSION_1F,
    0xA6: MapLocation.CINNABAR_GYM,
    0xA7: MapLocation.CINNABAR_LAB_1,
    0xA8: MapLocation.CINNABAR_LAB_2,
    0xA9: MapLocation.CINNABAR_LAB_3,
    0xAA: MapLocation.CINNABAR_LAB_4,
    0xAB: MapLocation.CINNABAR_POKECENTER,
    0xAC: MapLocation.CINNABAR_MART,
    0xAE: MapLocation.INDIGO_PLATEAU_LOBBY,
    0xAF: MapLocation.COPYCATS_HOUSE_1F,
    0xB0: MapLocation.COPYCATS_HOUSE_2F,
    0xB1: MapLocation.FIGHTING_DOJO,
    0xB2: MapLocation.SAFFRON_GYM,
    0xB3: MapLocation.SAFFRON_HOUSE_1,
    0xB4: MapLocation.SAFFRON_MART,
    0xB5: MapLocation.SILPH_CO_1F,
    0xB6: MapLocation.SAFFRON_POKECENTER,
    0xB7: MapLocation.SAFFRON_HOUSE_2,
    0xB8: MapLocation.ROUTE_15_GATE_1F,
    0xB9: MapLocation.ROUTE_15_GATE_2F,
    0xBA: MapLocation.ROUTE_16_GATE_1F,
    0xBB: MapLocation.ROUTE_16_GATE_2F,
    0xBC: MapLocation.ROUTE_16_HOUSE,
    0xBD: MapLocation.ROUTE_12_HOUSE,
    0xBE: MapLocation.ROUTE_18_GATE_1F,
    0xBF: MapLocation.ROUTE_18_GATE_2F,
    0xC0: MapLocation.SEAFOAM_ISLANDS_1F,
    0xC1: MapLocation.ROUTE_22_GATE,
    0xC2: MapLocation.VICTORY_ROAD_2F,
    0xC3: MapLocation.ROUTE_12_GATE_2F,
    0xC4: MapLocation.VERMILION_HOUSE_4,
    0xC5: MapLocation.DIGLETTS_CAVE,
    0xC6: MapLocation.VICTORY_ROAD_3F,
    0xC7: MapLocation.ROCKET_HIDEOUT_B1F,
    0xC8: MapLocation.ROCKET_HIDEOUT_B2F,
    0xC9: MapLocation.ROCKET_HIDEOUT_B3F,
    0xCA: MapLocation.ROCKET_HIDEOUT_B4F,
    0xCB: MapLocation.ROCKET_HIDEOUT_ELEVATOR,
    0xCF: MapLocation.SILPH_CO_2F,
    0xD0: MapLocation.SILPH_CO_3F,
    0xD1: MapLocation.SILPH_CO_4F,
    0xD2: MapLocation.SILPH_CO_5F,
    0xD3: MapLocation.SILPH_CO_6F,
    0xD4: MapLocation.SILPH_CO_7F,
    0xD5: MapLocation.SILPH_CO_8F,
    0xD6: MapLocation.POKEMON_MANSION_2F,
    0xD7: MapLocation.POKEMON_MANSION_3F,
    0xD8: MapLocation.POKEMON_MANSION_B1F,
    0xD9: MapLocation.SAFARI_ZONE_EAST,
    0xDA: MapLocation.SAFARI_ZONE_NORTH,
    0xDB: MapLocation.SAFARI_ZONE_WEST,
    0xDC: MapLocation.SAFARI_ZONE_CENTER,
    0xDD: MapLocation.SAFARI_ZONE_CENTER_REST_HOUSE,
    0xDE: MapLocation.SAFARI_ZONE_SECRET_HOUSE,
    0xDF: MapLocation.SAFARI_ZONE_WEST_REST_HOUSE,
    0xE0: MapLocation.SAFARI_ZONE_EAST_REST_HOUSE,
    0xE1: MapLocation.SAFARI_ZONE_NORTH_REST_HOUSE,
    0xE2: MapLocation.CERULEAN_CAVE_2F,
    0xE3: MapLocation.CERULEAN_CAVE_B1F,
    0xE4: MapLocation.CERULEAN_CAVE_1F,
    0xE5: MapLocation.NAME_RATERS_HOUSE,
    0xE6: MapLocation.CERULEAN_BADGE_HOUSE,
    0xE8: MapLocation.ROCK_TUNNEL_B1F,
    0xE9: MapLocation.SILPH_CO_9F,
    0xEA: MapLocation.SILPH_CO_10F,
    0xEB: MapLocation.SILPH_CO_11F,
    0xEC: MapLocation.SILPH_CO_ELEVATOR,
    0xEF: MapLocation.TRADE_CENTER,
    0xF0: MapLocation.COLOSSEUM,
    0xF5: MapLocation.LORELEIS_ROOM,
    0xF6: MapLocation.BRUNOS_ROOM,
    0xF7: MapLocation.AGATHAS_ROOM,
    0xF8: MapLocation.SUMMER_BEACH_HOUSE,
    0xFF: MapLocation.OUTSIDE,  # Used by indoor warp tiles to indicate that they lead outside.
}


class Map(BaseModel):
    """The state of the current map."""

    name: MapLocation
    height: int
    width: int
    grass_tile: int
    water_tile: int
    ledge_tiles: list[int]
    cut_tree_tiles: list[int]
    walkable_tiles: list[int]
    north_connection: MapLocation | None
    south_connection: MapLocation | None
    east_connection: MapLocation | None
    west_connection: MapLocation | None

    model_config = ConfigDict(frozen=True)


def parse_map_state(mem: PyBoyMemoryView) -> Map:
    """
    Parse the current map from a snapshot of the memory.

    :param mem: The PyBoyMemoryView instance to create the map from.
    :return: A new map.
    """
    tileset_id = mem[0xD3B4]

    # These were found by inspection.
    ledge_tiles = [54, 55] if tileset_id == 0 else []
    cut_tree_tiles = [45, 46, 61, 62] if tileset_id == 0 else []

    walkable_tile_ptr = mem[0xD57D] | (mem[0xD57E] << 8)
    walkable_tiles = []

    max_tiles = 0x180
    terminator = 0xFF
    for i in range(max_tiles):
        if mem[walkable_tile_ptr + i] == terminator:
            break
        walkable_tiles.append(mem[walkable_tile_ptr + i])

    return Map(
        name=_INT_TO_MAP_NAME[mem[0xD3AB]],
        height=mem[0xD571],
        width=mem[0xD572],
        grass_tile=mem[0xD582],
        water_tile=mem[3, 0x68A5],
        ledge_tiles=ledge_tiles,
        cut_tree_tiles=cut_tree_tiles,
        walkable_tiles=walkable_tiles,
        north_connection=_INT_TO_MAP_NAME[mem[0xD3BE]] if mem[0xD3BE] != terminator else None,
        south_connection=_INT_TO_MAP_NAME[mem[0xD3C9]] if mem[0xD3C9] != terminator else None,
        east_connection=_INT_TO_MAP_NAME[mem[0xD3DF]] if mem[0xD3DF] != terminator else None,
        west_connection=_INT_TO_MAP_NAME[mem[0xD3D4]] if mem[0xD3D4] != terminator else None,
    )
