from pathlib import Path

GAME_TICKS_PER_SECOND = 60

SCREEN_HEIGHT = 9
SCREEN_WIDTH = 10
PLAYER_OFFSET_Y = 4
PLAYER_OFFSET_X = 4

ITERATIONS_PER_CRITIQUE_CHECK = 20
ITERATIONS_PER_SUMMARY_UPDATE = 10
ITERATIONS_PER_GOAL_UPDATE = 5
ITERATIONS_PER_LONG_TERM_MEMORY_CREATION = 5
ITERATIONS_PER_BACKUP = 200

DEFAULT_NUM_MEMORIES_RETRIEVED = 10
DEFAULT_RERANKING_FACTOR = 2
DEFAULT_MIN_SEMANTIC_SIMILARITY = 0.5

RAW_MEMORY_MAX_SIZE = 100
SUMMARY_MEMORY_MAX_SIZE = 100

OUTPUTS_FOLDER = Path("outputs/")

DB_FILENAME = "memory.db"
DB_FILE_PATH = OUTPUTS_FOLDER / "database" / DB_FILENAME
DB_URL = f"sqlite+aiosqlite:///{DB_FILE_PATH}"

BACKUP_AGENT_STATE_NAME = "agent_state.json"
BACKUP_GAME_STATE_NAME = "game_state.state"

# Make sure all the relevant folders exist.
OUTPUTS_FOLDER.mkdir(exist_ok=True)
DB_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)
