"""Constants shared throughout the application."""

from pathlib import Path

DEFAULT_ROM_PATH = "resources/ylegacy.gbc"

SCREEN_HEIGHT = 9
SCREEN_WIDTH = 10
SCREEN_SHAPE = (SCREEN_HEIGHT, SCREEN_WIDTH)

PLAYER_OFFSET_Y = 4
PLAYER_OFFSET_X = 4

ITERATIONS_PER_SUMMARY_UPDATE = 10
ITERATIONS_PER_GOAL_UPDATE = 5
ITERATIONS_PER_LONG_TERM_MEMORY_RETRIEVAL = 10
BACKUP_INTERVAL_SECONDS = 20 * 60

MAX_LONG_TERM_MEMORIES_RETRIEVED = 10

RAW_MEMORY_MAX_SIZE = 50
SUMMARY_MEMORY_MAX_SIZE = 100

OUTPUTS_FOLDER = Path("outputs/")

DB_FOLDER_NAME = "database"
DB_FILE_PATH = OUTPUTS_FOLDER / DB_FOLDER_NAME / "memory.db"
DB_URL = f"sqlite+aiosqlite:///{DB_FILE_PATH}"

BACKUP_AGENT_STATE_NAME = "agent_state.json"
