"""Constants shared throughout the application."""

from pathlib import Path

DEFAULT_ROM_PATH = "resources/ylegacy.gbc"

SCREEN_HEIGHT = 9
SCREEN_WIDTH = 10
SCREEN_SHAPE = (SCREEN_HEIGHT, SCREEN_WIDTH)

PLAYER_OFFSET_Y = 4
PLAYER_OFFSET_X = 4

BACKUP_INTERVAL_SECONDS = 10 * 60

ROLLING_MEMORY_LEAF_SIZE = 20
ROLLING_MEMORY_RAW_BLOCK_SOFT_LIMIT = 100
ROLLING_MEMORY_SUMMARY_MAX_CHARACTERS = 2_000
ROLLING_MEMORY_COMPACTION_RANGE_LIMIT = 3
GAME_DIALOG_LABEL = "GAME DIALOG:"
ACTION_RESULT_LABEL = "ACTION RESULT:"
CONNECTION_CHECK_LABEL = "CONNECTION CHECK:"
SCRIPTED_LOOP_LABEL = "SCRIPTED LOOP DETECTED:"
CONNECTION_LOOP_LABEL = "CONNECTION LOOP DETECTED:"

LOOP_DETECTION_WINDOW_ITERATIONS = 10
LOOP_DETECTION_REPETITION_THRESHOLD = 3

OUTPUTS_FOLDER = Path("outputs/")

DB_FOLDER_NAME = "database"
DB_FILE_PATH = OUTPUTS_FOLDER / DB_FOLDER_NAME / "memory.db"
DB_URL = f"sqlite+aiosqlite:///{DB_FILE_PATH}"

BACKUP_AGENT_STATE_NAME = "agent_state.json"
